### ISSUE TITLE
Webpack 4 support

### ISSUE THREAD

**Issue by ShahdaSayed** [zadzbw/favicon-hash-webpack-plugin#1]
While using webpack 4, I get the following error:

`TypeError: compilation.fileDependencies.filter is not a function
    at removeOriginalFavicon (C:\Users\shahda.sayed\Documents\Project\baybridge\baybridge-bb\node_modules\favicon-hash-webpack-plugin\index.js:9:63)
    at compilation.plugin (C:\Users\shahda.sayed\Documents\Project\baybridge\baybridge-bb\node_modules\favicon-hash-webpack-plugin\index.js:39:11)
    at Promise (eval at create (C:\Users\shahda.sayed\Documents\Project\baybridge\baybridge-bb\node_modules\tapable\lib\HookCodeFactory.js:65:10), <anonymous>:11:16)
    at new Promise (<anonymous>)
    at AsyncSeriesWaterfallHook.eval [as promise] (eval at create (C:\Users\shahda.sayed\Documents\Project\baybridge\baybridge-bb\node_modules\tapable\lib\HookCodeFactory.js:65:10), <anonymous>:4:8)
    at AsyncSeriesWaterfallHook.lazyCompileHook (C:\Users\shahda.sayed\Documents\Project\baybridge\baybridge-bb\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Users\shahda.sayed\Documents\Project\baybridge\baybridge-bb\node_modules\html-webpack-plugin\index.js:673:47
    at Promise.resolve.then.then.then.then.then.then.html (C:\Users\shahda.sayed\Documents\Project\baybridge\baybridge-bb\node_modules\html-webpack-plugin\index.js:178:18)`

**Comment by zadzbw** [comment]
ok, i will do it in next version

**Comment by binarykitchen** [comment]
ping? any news on this?

**Comment by zadzbw** [comment]
> ping? any news on this?

i will fix it in this weekend

**Comment by zadzbw** [comment]
done, it supports webpack 4 now, just upgrade

**Comment by binarykitchen** [comment]
works well, many thanks
